# Generated by Django 4.2.7 on 2023-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_options_alter_product_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Артикул"
            ),
        ),
    ]
