# Generated by Django 4.2.7 on 2023-11-28 12:08

from django.db import migrations, models

from apps.services.fixtures import get_products_datasets


def create_categories(apps, schema_editor):
    Category: models.Model = apps.get_model("products", "Category")
    cats = [Category(id=i) for i in range(1, 60)]
    Category.objects.bulk_create(cats, ignore_conflicts=True)


def create_products(apps, schema_editor):
    Product: models.Model = apps.get_model("products", "Product")
    Product.objects.bulk_create(get_products_datasets(), ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_article"),
    ]

    operations = [
        migrations.RunPython(create_categories),
        migrations.RunPython(create_products),
    ]
