# Generated by Django 4.2.7 on 2023-11-28 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20231128_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="recommended_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Рекомендованная цена",
            ),
        ),
    ]
