# Generated by Django 4.2.7 on 2023-11-29 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_recommended_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("id",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
