version: '3.3'

services:
  db:
    container_name: quiz_db
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    # container_name: quiz_back
    # build:
    #   context: ./
    # command: gunicorn config.wsgi:application --bind 0:8000
    # restart: always
    # volumes:
    #   - static_data:/app/static/
    #   - media_data:/app/media/
    # depends_on:
    #   - db
    # env_file:
    #   - ./.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_NAME}

volumes:
  static_data:
  media_data:
  db_data:
