# Generated by Django 4.2.7 on 2023-11-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование дилера')),
                ('date', models.DateField(verbose_name='Дата получения цены')),
                ('product_url', models.URLField(max_length=255, verbose_name='Ссылка на сайт дилера')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='dealers.dealerkey', verbose_name='Ключ дилера')),
            ],
            options={
                'verbose_name': 'Цена дилера',
                'verbose_name_plural': 'Цены дилеров',
                'ordering': ('-date',),
            },
        ),
    ]
