# Generated by Django 4.2.7 on 2023-11-29 13:20

from django.db import migrations, models

from apps.services.fixtures_parser import get_prices_datasets


def create_prices(apps, schema_editor):
    DealerPrice: models.Model = apps.get_model("prices", "DealerPrice")
    prices_datasets = get_prices_datasets()
    if prices_datasets:
        prices = [DealerPrice(**fields) for fields in prices_datasets]
        DealerPrice.objects.bulk_create(prices, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0001_initial"),
        ("dealers", "0003_dealerkey_unique_pair_dealer_and_key"),
    ]

    operations = [
        migrations.RunPython(create_prices),
    ]
