# Generated by Django 4.2.7 on 2023-11-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0002_auto_20231128_1528"),
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dealerprice",
            options={
                "verbose_name": "Цена дилера",
                "verbose_name_plural": "Цены дилеров",
            },
        ),
        migrations.AlterField(
            model_name="dealerprice",
            name="key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="dealers.dealerkey",
                verbose_name="Ключ дилера",
            ),
        ),
    ]
