# Generated by Django 4.2.7 on 2023-11-28 13:32

from django.db import migrations, models

from apps.services.fixtures import get_prices_datasets


def create_prices(apps, schema_editor):
    DealerPrice: models.Model = apps.get_model("prices", "DealerPrice")
    DealerPrice.objects.bulk_create(
        get_prices_datasets(), ignore_conflicts=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0002_alter_dealerprice_options_alter_dealerprice_key"),
    ]

    operations = [
        migrations.RunPython(create_prices),
    ]
