# Generated by Django 4.2.7 on 2023-12-02 11:10

from django.conf import settings
from django.db import migrations

from apps.users.models import CustomUser


def create_first_superuser(apps, schema_editor):
    CustomUser.objects.create_superuser(
        email=settings.ADMIN_EMAIL,
        password=settings.ADMIN_PASSWORD,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_first_superuser)]
