# Generated by Django 4.2.7 on 2023-11-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование дилера')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DealerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, verbose_name='Ключ дилера')),
                ('is_provided', models.BooleanField(default=False, verbose_name='Есть в исходном csv')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealer', verbose_name='Дилер')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ключ дилера',
                'verbose_name_plural': 'Ключи дилера',
                'ordering': ('id',),
                'default_related_name': 'dealer_keys',
            },
        ),
        migrations.AddConstraint(
            model_name='dealerkey',
            constraint=models.UniqueConstraint(fields=('dealer_id', 'key'), name='unique_pair_dealer_and_key'),
        ),
    ]
