# Generated by Django 4.2.7 on 2023-11-28 12:28

from django.db import migrations, models

from apps.services.fixtures import (
    get_dealers_datasets,
    get_dealers_keys_datasets,
)


def create_dealers(apps, schema_editor):
    Dealer: models.Model = apps.get_model("dealers", "Dealer")
    Dealer.objects.bulk_create(get_dealers_datasets(), ignore_conflicts=True)


def create_dealer_keys(apps, schema_editor):
    DealerKey: models.Model = apps.get_model("dealers", "DealerKey")
    DealerKey.objects.bulk_create(
        get_dealers_keys_datasets(), ignore_conflicts=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_dealers),
        migrations.RunPython(create_dealer_keys),
    ]
