# Generated by Django 4.2.7 on 2023-11-28 12:28

from django.db import migrations, models

from apps.services.fixtures_parser import (
    get_dealers_datasets,
    get_dealers_keys_datasets,
)


def create_dealers(apps, schema_editor):
    Dealer: models.Model = apps.get_model("dealers", "Dealer")
    dealers_datasets = get_dealers_datasets()
    if dealers_datasets:
        dealers = [Dealer(**fields) for fields in dealers_datasets]
        Dealer.objects.bulk_create(dealers, ignore_conflicts=True)


def create_dealer_keys(apps, schema_editor):
    DealerKey: models.Model = apps.get_model("dealers", "DealerKey")
    keys_datasets = get_dealers_keys_datasets()
    if keys_datasets:
        dealers_keys = [DealerKey(**fields) for fields in keys_datasets]
        DealerKey.objects.bulk_create(dealers_keys, ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0001_initial"),
        ("products", "0004_auto_20231128_1508"),
    ]

    operations = [
        migrations.RunPython(create_dealers),
        migrations.RunPython(create_dealer_keys),
    ]
