# Generated by Django 4.2.7 on 2023-11-29 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0003_dealerkey_unique_pair_dealer_and_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dealer",
            options={
                "ordering": ("id",),
                "verbose_name": "Дилер",
                "verbose_name_plural": "Дилеры",
            },
        ),
        migrations.AlterModelOptions(
            name="dealerkey",
            options={
                "default_related_name": "dealer_keys",
                "ordering": ("id",),
                "verbose_name": "Ключ дилера",
                "verbose_name_plural": "Ключи дилера",
            },
        ),
    ]
