# Generated by Django 4.2.7 on 2023-12-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_category_options_alter_product_options"),
        ("dealers", "0004_alter_dealer_options_alter_dealerkey_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metrics",
                    models.FloatField(verbose_name="Метрика совпадения"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "На проверку"),
                            ("yes", "Подтверждено"),
                            ("no", "Не подходит"),
                        ],
                        default="new",
                        max_length=3,
                        verbose_name="Статус предложения",
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dealers.dealerkey",
                        verbose_name="Ключ дилера",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение соответствия",
                "verbose_name_plural": "Предложения соответствия",
                "ordering": ("-metrics", "id"),
                "default_related_name": "matches",
            },
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("key_id", "product_id"),
                name="unique_pair_key_and_product",
            ),
        ),
    ]
