# Generated by Django 4.2.7 on 2023-12-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0005_match_match_unique_pair_key_and_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={
                "default_related_name": "matches",
                "ordering": ("-similarity", "id"),
                "verbose_name": "Предложение соответствия",
                "verbose_name_plural": "Предложения соответствия",
            },
        ),
        migrations.RemoveField(
            model_name="match",
            name="metrics",
        ),
        migrations.AddField(
            model_name="match",
            name="similarity",
            field=models.IntegerField(
                default=0, verbose_name="Метрика соответствия в %"
            ),
            preserve_default=False,
        ),
    ]
