# Generated by Django 4.2.7 on 2023-12-07 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dealers", "0006_alter_match_options_remove_match_metrics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerkey",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealerkey",
            name="edited_at",
            field=models.DateField(auto_now=True, verbose_name="Дата подбора"),
        ),
    ]
